### ISSUE TITLE
Bug: Missing AnvilBase Attribute

### ISSUE THREAD

**Issue by kacperpaczos** [cwacek/python-jsonschema-objects#271] opened 2023-12-25 15:35 UTC
**Describe the bug**
I am encountering an issue with a JSON schema. In the schema, I have the following entry:
` "title": "AnvilBase"`
According to the namespace, there should be a corresponding attribute:
`AnvilBase = ns.AnvilBase`
However, it appears that this attribute is missing, resulting in the following error:
```
l.py", line 146, in __getattribute__
    raise AttributeError(msg % (type(self).__name__, name))
AttributeError: 'Namespace' object has no attribute 'AnvilBase'. Did you mean: 'Anvilbase'?
```

**Comment by cwacek** [comment] 2023-12-26 21:14
This is not a bug. See comment closing #273

**Closed by cwacek** 2023-12-26 21:14 UTC
Labels: bug

**Comment by kacperpaczos** [comment] 2023-12-26 23:12
So, please add a table of possible titles and transform it into code in the documentation. Otherwise, I will do it later.

**Comment by cwacek** [comment] 2023-12-27 15:15
The way names are transformed is already described in the README. See https://github.com/cwacek/python-jsonschema-objects?tab=readme-ov-file#accessing-generated-objects. 

See the note about passing `standardized_names=False` if you don't want it to change the titles.
